import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/components/Provider";
import { Toaster } from "react-hot-toast"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "PDF TO CHAT App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <Provider>
                <html lang="en">
                    <body className={inter.className}>
                        {children}
                        <Toaster position="bottom-center"/>
                    </body>
                </html>
            </Provider>
        </ClerkProvider>
    );
}
